### PR TITLE
Fix PaymentIntentsRoute infinite loop when creating new request

### PR DESCRIPTION
**Pull request by kschins**
The actual request was never created due to an infinite loop produced by repeatedly calling the incorrect method.

### CODE REVIEW

**Comment by Andrewangeta** [comment]
@ksmandersen you ok with this version of your backport?

**Comment by ksmandersen** [comment]
@Andrewangeta Looks good to me.

I had actually made these changes on my local fork but forgot to include them in the PR. Sorry about that @kschins

**Comment by kschins** [comment]
@Andrewangeta can we merge this now then, please?

**Comment by Andrewangeta** [comment]
Yep.

**Pull request merged**
