### PR TITLE
Fixes destination charges platform fee issue

### LINKED ISSUE #23: Collecting platform fees with Connect destination charges
As already discussed with @anthonycastelli and @Andrewangeta, the platform fee collection when creating destination charges is currently broken.

[The documentation](https://stripe.com/docs/connect/destination-charges#collecting-platform-fees) says that this should be achieved by simply specifying the total `amount`, together with `destination[account]` and `destination[amount]` where latter should be calculated by subtracting the platform’s fee from the total charge amount. No explicit "application fee" parameter is needed.

Please find my PR that fixes this issue referenced below. ✌️

### PR DESCRIPTION
**Pull request by damirstuhec**
Fixes #23

### CODE REVIEW

**Review by anthonycastelli — COMMENTED** [review]
Things look good 👍 Have you tested this and verified it works? Circle is having a hard time today so the tests haven't passed.

**Comment by damirstuhec** [comment]
I’m in contact with Stripe as it seems like there is some issue on their side as well. Will keep you posted. In the meantime please leave this PR open.

**Comment by Andrewangeta** [comment]
Looks good. In the Vapor 3 version of Stripe there will  no longer be a dependency on the stipe api for tests.

**Comment by damirstuhec** [comment]
@anthonycastelli @Andrewangeta ok, so it turns out that a "platform fee", when making destination charges with Connect, is not really presented anywhere as a "fee".

In the dashboard, you cannot see collected "platform fee" anywhere in the Connect section (I was expecting to see it in "collected fees" in Connect).

However, after talking to Stripe's team, we finally figured out that you can see those "fees" just as normal proceeds (not as a fee) to your platform's bank account in the *Balance* section (see image below).

screen shot 2017-12-23 at 10 47 03

So [Stripe's docs are clearly misleading](https://stripe.com/docs/connect/destination-charges#collecting-platform-fees) because they talk specifically about "collecting fees" and I've let them know about that.

While this PR doesn't solve any functional issues because it turns out there were none, it does fix the wrong parameter documentation and it also fixes the ability to set `destination[account]` and `destination[amount]` independently (when making a destination charge without collecting a platform "fee", one can skip adding the `destination[amount]` parameter).

**Comment by damirstuhec** [comment]
That said, you guys can go ahead and merge this PR if you agree with the changes.

**Comment by anthonycastelli** [comment]
@Andrewangeta Since you’ve been working on the Vapor 3 conversion, I’ll let you handle this.

**Comment by Andrewangeta** [comment]
@anthonycastelli  This seems to be handled in V3 
https://github.com/vapor-community/stripe-provider/blob/40873d9edb903628a2e928587dc2bc1a4f3a1044/Sources/Stripe/API/Routes/ChargeRoutes.swift#L62-L68

**Comment by anthonycastelli** [comment]
I guess it's safe to close this then?

**Comment by Andrewangeta** [comment]
Yea more or less. I’m really for leaving V2 behind at this point 😅 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
