### PR TITLE
Added Coupons

### PR DESCRIPTION
**Pull request by Andrewangeta**

### CODE REVIEW

**Review by anthonycastelli — COMMENTED** [review]
My only comment is your open `{` For consistency, can you move them to the same line as the function declaration? 

i.e.
```swift
func foo() {
   ...
}
```
vs
```swift
func foo()
{
    ...
}
```

same thing for the if let statements

**Comment by Andrewangeta** [comment]
Yea i can sorry, its a habit lol. I argue at work about it all the time.

**Comment by anthonycastelli** [comment]
No worries. Some people like it on a new line, some like it on the same 😛 I just stick to Apple's style whenever possible.

**Comment by anthonycastelli** [comment]
👍

**Pull request merged**
